### ISSUE TITLE
Implement a way to reset the StateHandler data

### ISSUE THREAD

**Issue by bdbch** [bdbch/js-state-handler#12]
I thought it would be nice to do something like `State.reset()` to reset the data back to the initial state.

**Comment by ccmetz** [comment]
I'd be interested in working on this one. Just wanted some clarification on what exactly you would want `reset` to do. Would it just set the state back to the first item and then render it? I'm still looking through the documentation.

**Comment by bdbch** [comment]
@ccmetz it's pretty simple, there should be a way to just reset the `State.data` value back to the initial state which was defined on the constructor.
