### ISSUE TITLE
Allow Renderer to also add all keys to the renderer

### ISSUE THREAD

**Issue by bdbch** [bdbch/js-state-handler#17]
Right now you need to add something like this:

```js
var State = new StateHandler({
  key: 'val',
  key2: 4
}, [
  {
    keys: ['key', 'key2'],
    method: doSomething
  }
])
```

How about we could use something like this: `keys: '*'` or something to bind the render function on all store keys.

**Comment by pwelby** [comment]
I'd be happy to work on this. At first glance, it appears you want something along the lines of:
```javascript
if (fn.keys === '*') {
  fn.keys = [];
  for(const key of Object.keys(this.data)) {
    fn.keys.push(key);
  }
}
```
in `addToRenderer()`, with a similar change made to the case where an array of functions is passed. Would that be correct?

**Comment by bdbch** [comment]
@pwelby exactly! :) Thank you!
