### ISSUE TITLE
Implement State specific rendering

### ISSUE THREAD

**Issue by bdbch** [bdbch/js-state-handler#2]
Right now each change of the state will cause a render on all defined functions.

It would be cool if we could control which render functions will be called when a specific state value is changed.

## Example

**Old**:

```js
var State = new StateHandler({
  apples: 4,
  bananas: 8,
  friends: []
}, [
  renderFruits,
  renderFriends
])
```

**News**:

```js
var State = new StateHandler({
  apples: 4,
  bananas: 8,
  friends: []
}, [
  {
    keys: ['apples', 'bananas'],
    method: renderFruits
  },
  {
    keys: 'friends',
    method: renderFriends
  }
])
```

**Comment by juancuiule** [comment]
I'll take a look at this and see what I can do :smiley:

**Comment by bdbch** [comment]
Nice, thank you! :)
