### ISSUE TITLE
Implement a test script

### ISSUE THREAD

**Issue by bdbch** [bdbch/js-state-handler#23]
So now since we have Travis setup but a missing test, we should write one.

First - Should we use a Test runner like Ava or Mocha or use simple, custom test script? Could someone with a bit more experience propose something?

Then we should check if the State can:

* Be created with initial data
* Add multiple render functions on Constructor
* Add a render function via the `State.addToRenderer` method 
* Update data via `State.set`
* Can be read via `State.data`

**Comment by geoffdavis92** [comment]
I could give this a shot using [Jest](https://facebook.github.io/jest/). I've only begun writing unit tests for a side project of mine, but Jest has been easy to understand and implement.

**Comment by bdbch** [comment]
Sure! Thank you!
