### ISSUE TITLE
Implement a easy way to push data into a store key

### ISSUE THREAD

**Issue by bdbch** [bdbch/js-state-handler#24]
Right now if you want to push a item into an array, you need to do something like this:

```js
State.set({
  items: State.data.items.push('my item')
})
```

This is okay but could be easier to write, what do you think?

How about a solution which behaves like this:

```js
// single string
State.pushNewState(State.data.items, 'my item')

// object
State.pushNewState(State.data.items, {
  name: 'Max',
  welcome: 'Hello!'
})
```

**Comment by gigobyte** [comment]
How about a `update` method instead, it's way more generic? Something like this:
```
State.update({
      items: x => x.push('my item')
})
```

**Comment by bdbch** [comment]
Would also be okay
