### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by bdbch** [bdbch/js-state-handler#3]
Right now the documentation is really bad and doesn't explain a lot. I would prefer smaller code examples and use cases so it's easier to follow and understand.

**Comment by ohadleshno** [comment]
would like to help in this can you give any guidance ?

**Comment by bdbch** [comment]
The documentation on the README.md isn't updated yet plus is confusing and to large for the first look.

I would like to make it smaller and more easier to read. You can pick this one up if you want to! if you need help with the docs, let me know.

**Comment by bdbch** [comment]
I closed this in #10
